version: "3.9"
services:
  dev:
    build:
      context: .
      target: dev
    image: bot_ite_dog:dev
    volumes:
      - type: bind
        source: ./src
        target: /src
      - type: bind
        source: ./text
        target: /text
    tty: true
    stdin_open: true
